### ISSUE TITLE
BankAccount needs a name field

### ISSUE THREAD

**Issue by stephenwade** [acovrig/DatabaseProject#7]
Right now, the Account dropdown in Transaction/Create just shows the type of account, which is useless if the user has >1 of any type of account.

![image](https://cloud.githubusercontent.com/assets/4148577/7337782/5c385dd2-ec04-11e4-95d0-5f431bd27f7d.png)

**Comment by acovrig** [comment]
Fixed by 2f9bcbe2fd56f16f41ef8c2b954f32e6a65d698d
